# Generated by Django 4.0.5 on 2022-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='address',
            name='description',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Descrição'),
        ),
    ]
